src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: FormationRepository::class)]
class Formation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $schoolName = null;

    #[ORM\Column(length: 255)]
    private ?string $location = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $startDate = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $endDate = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $resume = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getSchoolName(): ?string
    {
        return $this->schoolName;
    }

    public function setSchoolName(string $schoolName): static
    {
        $this->schoolName = $schoolName;

        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(string $location): static
    {
        $this->location = $location;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): static
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(?\DateTimeInterface $endDate): static
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getYearStart(): ?int
    {
        return $this->startDate ? $this->startDate->format('Y') : null;
    }

    public function getYearEnd(): ?int
    {
        return $this->endDate ? $this->endDate->format('Y') : null;
    }

    public function getResume(): ?string
    {
        return $this->resume;
    }

    public function setResume(string $resume): static
    {
        $this->resume = $resume;

        return $this;
    }
}

src/Controller/PortfolioController.php
<?php

namespace App\Controller;

use App\Repository\FormationRepository;
use App\Repository\PersonalInfoRepository;
use App\Repository\WorkExperienceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PortfolioController extends AbstractController
{
    #[Route('/', name: 'app_portfolio')]
    public function index(PersonalInfoRepository $personalInfoRepository, WorkExperienceRepository $workExperienceRepository, FormationRepository $formationRepository): Response
    {

        $personalInfo = $personalInfoRepository->findAll();
        $workExperience = $workExperienceRepository->findAll();
        $formation = $formationRepository->findAll();

        return $this->render('portfolio/index.html.twig', [
            'personalInfo' => $personalInfo,
            'workExperience' => $workExperience,
            'formation' => $formation
        ]);
    }
}

templates/portfolio/_about.html.twig
<div id="fh5co-about" class="animate-box">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
				<h2>A propos de moi</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<ul class="info">
					<li>
						<span class="first-block">Nom:</span>
						<span class="second-block">{{personalInfo[0].firstName}}
							{{personalInfo[0].lastName}}</span>
					</li>
					<li>
						{% if personalInfo[0].phone %}
							<span class="first-block">Telephone:</span>
							<span class="second-block">{{personalInfo[0].phone}}</span>
						</li>
					{% endif %}
					<li>
						{% if personalInfo[0].mail %}
							<span class="first-block">Email:</span>
							<span class="second-block">{{personalInfo[0].mail}}</span>
						</li>
					{% endif %}
					{% if personalInfo[0].website %}
						<li>
							<span class="first-block">Site Web:</span>
							<span class="second-block">{{personalInfo[0].website}}</span>
						</li>
					{% endif %}
					{% if personalInfo[0].address %}
						<li>
							<span class="first-block">Adresse:</span>
							<span class="second-block">{{personalInfo[0].address}}</span>
						</li>
					{% endif %}
				</ul>
			</div>
			<div class="col-md-8">
				<h2>Hello There!</h2>
				<p>{{personalInfo[0].resume}}</p>
				<ul class="fh5co-social-icons">
					{% if personalInfo[0].githubLink %}
						<li>
							<a href="{{personalInfo[0].githubLink}}">
								<i class="icon-github2"></i>
							</a>
						</li>
					{% endif %}
					{% if personalInfo[0].linkedinLink %}
						<li>
							<a href="{{personalInfo[0].linkedinLink}}">
								<i class="icon-linkedin2"></i>
							</a>
						</li>
					{% endif %}
					{% if personalInfo[0].maltLink %}
						<li>
							<a href="{{personalInfo[0].maltLink}}">
								<i class="icon-monitor"></i>
							</a>
						</li>
					{% endif %}
				</ul>
			</p>
		</div>
	</div>
</div></div>

templates/portfolio/_blog.html.twig
<div id="fh5co-blog">
	<div class="container">
		<div class="row animate-box">
			<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
				<h2>Post on Medium</h2>
				<p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p>
			</div>
		</div>
		<div class="row">
			<div class="col-md-4">
				<div class="fh5co-blog animate-box">
					<a href="#" class="blog-bg" style="background-image: url(images/portfolio-1.jpg);"></a>
					<div class="blog-text">
						<span class="posted_on">Mar. 15th 2016</span>
						<h3>
							<a href="#">Photoshoot On The Street</a>
						</h3>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						<ul class="stuff">
							<li>
								<i class="icon-heart2"></i>249</li>
							<li>
								<i class="icon-eye2"></i>308</li>
							<li>
								<a href="#">Read More<i class="icon-arrow-right22"></i>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="fh5co-blog animate-box">
					<a href="#" class="blog-bg" style="background-image: url(images/portfolio-2.jpg);"></a>
					<div class="blog-text">
						<span class="posted_on">Mar. 15th 2016</span>
						<h3>
							<a href="#">Surfing at Philippines</a>
						</h3>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						<ul class="stuff">
							<li>
								<i class="icon-heart2"></i>249</li>
							<li>
								<i class="icon-eye2"></i>308</li>
							<li>
								<a href="#">Read More<i class="icon-arrow-right22"></i>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-md-4">
				<div class="fh5co-blog animate-box">
					<a href="#" class="blog-bg" style="background-image: url(images/portfolio-3.jpg);"></a>
					<div class="blog-text">
						<span class="posted_on">Mar. 15th 2016</span>
						<h3>
							<a href="#">Capture Living On Uderwater</a>
						</h3>
						<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
						<ul class="stuff">
							<li>
								<i class="icon-heart2"></i>249</li>
							<li>
								<i class="icon-eye2"></i>308</li>
							<li>
								<a href="#">Read More<i class="icon-arrow-right22"></i>
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

templates/portfolio/_contact.html.twig
<div id="fh5co-consult">
	<div class="video fh5co-video" style="background-image: url(images/cover_bg_1.jpg);">
		<div class="overlay"></div>
	</div>
	<div class="choose animate-box">
		<h2>Contact</h2>
		<form action="#">
			<div class="row form-group">
				<div class="col-md-6">
					<input type="text" id="fname" class="form-control" placeholder="Your firstname">
				</div>
			</div>
			<div class="row form-group">
				<div class="col-md-6">
					<input type="text" id="lname" class="form-control" placeholder="Your lastname">
				</div>
			</div>

			<div class="row form-group">
				<div class="col-md-12">
					<input type="text" id="email" class="form-control" placeholder="Your email address">
				</div>
			</div>

			<div class="row form-group">
				<div class="col-md-12">
					<input type="text" id="subject" class="form-control" placeholder="Your subject of this message">
				</div>
			</div>

			<div class="row form-group">
				<div class="col-md-12">
					<textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Say something about us"></textarea>
				</div>
			</div>
			<div class="form-group">
				<input type="submit" value="Send Message" class="btn btn-primary">
			</div>

		</form>
	</div>
</div>

templates/portfolio/_features.html.twig
<div id="fh5co-features" class="animate-box">
	<div class="container">
		<div class="services-padding">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
					<h2>My Services</h2>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 text-center">
					<div class="feature-left">
						<span class="icon">
							<i class="icon-paintbrush"></i>
						</span>
						<div class="feature-copy">
							<h3>Web Design</h3>
							<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit.</p>
						</div>
					</div>
				</div>

				<div class="col-md-4 text-center">
					<div class="feature-left">
						<span class="icon">
							<i class="icon-briefcase"></i>
						</span>
						<div class="feature-copy">
							<h3>Branding</h3>
							<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit.</p>
						</div>
					</div>

				</div>
				<div class="col-md-4 text-center">
					<div class="feature-left">
						<span class="icon">
							<i class="icon-search"></i>
						</span>
						<div class="feature-copy">
							<h3>Analytics</h3>
							<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit.</p>
						</div>
					</div>
				</div>
			</div>


			<div class="row">
				<div class="col-md-4 text-center">

					<div class="feature-left">
						<span class="icon">
							<i class="icon-bargraph"></i>
						</span>
						<div class="feature-copy">
							<h3>Web Developent</h3>
							<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit.</p>
						</div>
					</div>

				</div>

				<div class="col-md-4 text-center">
					<div class="feature-left">
						<span class="icon">
							<i class="icon-genius"></i>
						</span>
						<div class="feature-copy">
							<h3>Web Marketing</h3>
							<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit.</p>
						</div>
					</div>

				</div>
				<div class="col-md-4 text-center">
					<div class="feature-left">
						<span class="icon">
							<i class="icon-chat"></i>
						</span>
						<div class="feature-copy">
							<h3>Support</h3>
							<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

templates/portfolio/_footer.html.twig
<div id="fh5co-footer">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<p>&copy; 2017 Free HTML5 Template. All Rights Reserved.
					<br>Designed by
					<a href="http://freehtml5.co" target="_blank">FreeHTML5.co</a>
					Demo Images:
					<a href="http://unsplash.com" target="_blank">Unsplash</a>
				</p>
			</div>
		</div>
	</div>
</div>

<div class="gototop js-top">
	<a href="#" class="js-gotop">
		<i class="icon-arrow-up22"></i>
	</a>
</div>

templates/portfolio/_header.html.twig
<header id="fh5co-header" class="fh5co-cover js-fullheight" role="banner" style="background-image:url(images/cover_bg_3.jpg);" data-stellar-background-ratio="0.5">
	<div class="overlay"></div>
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center">
				<div class="display-t js-fullheight">
					<div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
						<div class="profile-thumb" style="background: url(images/user.jpg);"></div>
						<h1>
							{% if personalInfo|length > 0 %}
								<span>{{ personalInfo[0].firstName }}
									{{ personalInfo[0].lastName }}</span>
							{% else %}
								<p>John Doe</p>
							{% endif %}
						</h1>
						<h3>
							<span>{{personalInfo[0].job}}</span>
						</h3>
						<p>
							<ul class="fh5co-social-icons">
								{% if personalInfo[0].githubLink %}
									<li>
										<a href="{{personalInfo[0].githubLink}}">
											<i class="icon-github2"></i>
										</a>
									</li>
								{% endif %}
								{% if personalInfo[0].linkedinLink %}
									<li>
										<a href="{{personalInfo[0].linkedinLink}}">
											<i class="icon-linkedin2"></i>
										</a>
									</li>
								{% endif %}
								{% if personalInfo[0].maltLink %}
									<li>
										<a href="{{personalInfo[0].maltLink}}">
											<i class="icon-monitor"></i>
										</a>
									</li>
								{% endif %}
							</ul>
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</header>

templates/portfolio/_hire.html.twig
<div id="fh5co-started" class="fh5co-bg-dark">
	<div class="overlay"></div>
	<div class="container">
		<div class="row animate-box">
			<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
				<h2>Hire Me!</h2>
				<p>Facilis ipsum reprehenderit nemo molestias. Aut cum mollitia reprehenderit. Eos cumque dicta adipisci architecto culpa amet.</p>
				<p>
					<a href="#" class="btn btn-default btn-lg">Contact Us</a>
				</p>
			</div>
		</div>
	</div>
</div>

templates/portfolio/_map.html.twig
<div id="map" class="fh5co-map"></div></div>

templates/portfolio/_resume.html.twig
<div id="fh5co-resume" class="fh5co-bg-color">
	<div class="container">
		<div class="row animate-box">
			<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
				<h2>My Resume</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12 col-md-offset-0">
				<ul class="timeline">
					<li class="timeline-heading text-center animate-box">
						<div>
							<h3>Work Experience</h3>
						</div>
					</li>
					{% set totalExperiences = workExperience|length %}
					{% set isFirstFormationEven = totalExperiences is even %}

					{% for experience in workExperience %}
						{% set isEven = loop.index is even %}

						<li class="animate-box {% if isEven %}timeline-unverted{% else %}timeline-inverted animate-box{% endif %}">
							<div class="timeline-badge">
								<i class="icon-suitcase"></i>
							</div>
							<div class="timeline-panel">
								<div class="timeline-heading">
									<h3 class="timeline-title">{{ experience.title }}</h3>
									<span class="company">{{ experience.companyName }}
										-
										{{ experience.location }}
										-
										{{ experience.yearStart }}
										-
										{{ experience.yearEnd }}</span>
								</div>
								<div class="timeline-body">
									<p>{{ experience.resume }}</p>
								</div>
							</div>
						</li>
					{% endfor %}

					<br>

					<li class="timeline-heading text-center animate-box">
						<div>
							<h3>Education</h3>
						</div>
					</li>

					{% set isFirstFormationLeft = (isFirstFormationEven and totalExperiences is odd) or (not isFirstFormationEven and totalExperiences is even) %}

					{% for item in formation %}
						{% set formationIndex = loop.index0 %}

						*
						{% set isLeftFormation = isFirstFormationLeft ? (formationIndex is odd) : (formationIndex is even) %}

						<li class="animate-box {% if isLeftFormation %}timeline-unverted{% else %}timeline-inverted animate-box{% endif %}">
							<div class="timeline-badge">
								<i class="icon-graduation-cap"></i>
							</div>
							<div class="timeline-panel">
								<div class="timeline-heading">
									<h3 class="timeline-title">{{ item.title }}</h3>
									<span class="company">{{ item.schoolName }}
										-
										{{ item.location }}
										-
										{{ item.yearStart }}
										-
										{{ item.yearEnd }}</span>
								</div>
								{% if item.resume %}
									<div class="timeline-body">
										<p>{{ item.resume }}</p>
									</div>
								{% endif %}
							</div>
						</li>
					{% endfor %}

				</ul>
			</div>
		</div>
	</div>
</div>

templates/portfolio/_skills.html.twig
<div id="fh5co-skills" class="animate-box">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
				<h2>Skills</h2>
			</div>
		</div>
		<div class="row row-pb-md">
			<div class="col-md-3 col-sm-6 col-xs-12 text-center">
				<div class="chart" data-percent="95">
					<span>
						<strong>HTML5</strong>95%</span>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12 text-center">
				<div class="chart" data-percent="93">
					<span>
						<strong>CSS3</strong>93%</span>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12 text-center">
				<div class="chart" data-percent="90">
					<span>
						<strong>jQuery</strong>90%</span>
				</div>
			</div>

			<div class="col-md-3 col-sm-6 col-xs-12 text-center">
				<div class="chart" data-percent="89">
					<span>
						<strong>PHP</strong>89%</span>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12 text-center">
				<div class="chart" data-percent="85">
					<span>
						<strong>MySQL</strong>85%</span>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12 text-center">
				<div class="chart" data-percent="90">
					<span>
						<strong>AngularJS</strong>90%</span>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12 text-center">
				<div class="chart" data-percent="85">
					<span>
						<strong>Ruby</strong>85%</span>
				</div>
			</div>
			<div class="col-md-3 col-sm-6 col-xs-12 text-center">
				<div class="chart" data-percent="90">
					<span>
						<strong>Java</strong>90%</span>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-md-6">
				<div class="progress-wrap">
					<h3>
						<span class="name-left">HTML5/CSS3</span>
						<span class="value-right">95%</span>
					</h3>
					<div class="progress">
						<div class="progress-bar progress-bar-1 progress-bar-striped active" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:90%"></div>
					</div>
				</div>
				<div class="progress-wrap">
					<h3>
						<span class="name-left">WordPress</span>
						<span class="value-right">90%</span>
					</h3>
					<div class="progress">
						<div class="progress-bar progress-bar-2 progress-bar-striped active" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:90%"></div>
					</div>
				</div>
				<div class="progress-wrap">
					<h3>
						<span class="name-left">PHP</span>
						<span class="value-right">80%</span>
					</h3>
					<div class="progress">
						<div class="progress-bar progress-bar-3 progress-bar-striped active" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width:80%"></div>
					</div>
				</div>
				<div class="progress-wrap">
					<h3>
						<span class="name-left">Java</span>
						<span class="value-right">85%</span>
					</h3>
					<div class="progress">
						<div class="progress-bar progress-bar-4 progress-bar-striped active" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width:85%"></div>
					</div>
				</div>
			</div>
			<div class="col-md-6">
				<div class="progress-wrap">
					<h3>
						<span class="name-left">Design</span>
						<span class="value-right">100%</span>
					</h3>
					<div class="progress">
						<div class="progress-bar progress-bar-5 progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width:100%"></div>
					</div>
				</div>
				<div class="progress-wrap">
					<h3>
						<span class="name-left">Ruby</span>
						<span class="value-right">70%</span>
					</h3>
					<div class="progress">
						<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%"></div>
					</div>
				</div>
				<div class="progress-wrap">
					<h3>
						<span class="name-left">Python</span>
						<span class="value-right">85%</span>
					</h3>
					<div class="progress">
						<div class="progress-bar progress-bar-1 progress-bar-striped active" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width:85%"></div>
					</div>
				</div>
				<div class="progress-wrap">
					<h3>
						<span class="name-left">jQuery</span>
						<span class="value-right">75%</span>
					</h3>
					<div class="progress">
						<div class="progress-bar progress-bar-3 progress-bar-striped active" role="progressbar" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100" style="width:75%"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

templates/portfolio/_works.html.twig
<div id="fh5co-work" class="fh5co-bg-dark">
	<div class="container">
		<div class="row animate-box">
			<div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
				<h2>Work</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3 text-center col-padding animate-box">
				<a href="#" class="work" style="background-image: url(images/portfolio-1.jpg);">
					<div class="desc">
						<h3>Project Name</h3>
						<span>Illustration</span>
					</div>
				</a>
			</div>
			<div class="col-md-3 text-center col-padding animate-box">
				<a href="#" class="work" style="background-image: url(images/portfolio-2.jpg);">
					<div class="desc">
						<h3>Project Name</h3>
						<span>Brading</span>
					</div>
				</a>
			</div>
			<div class="col-md-3 text-center col-padding animate-box">
				<a href="#" class="work" style="background-image: url(images/portfolio-3.jpg);">
					<div class="desc">
						<h3>Project Name</h3>
						<span>Illustration</span>
					</div>
				</a>
			</div>
			<div class="col-md-3 text-center col-padding animate-box">
				<a href="#" class="work" style="background-image: url(images/portfolio-4.jpg);">
					<div class="desc">
						<h3>Project Name</h3>
						<span>Design</span>
					</div>
				</a>
			</div>
			<div class="col-md-3 text-center col-padding animate-box">
				<a href="#" class="work" style="background-image: url(images/portfolio-5.jpg);">
					<div class="desc">
						<h3>Project Name</h3>
						<span>Website</span>
					</div>
				</a>
			</div>
			<div class="col-md-3 text-center col-padding animate-box">
				<a href="#" class="work" style="background-image: url(images/portfolio-6.jpg);">
					<div class="desc">
						<h3>Project Name</h3>
						<span>Illustration</span>
					</div>
				</a>
			</div>
			<div class="col-md-3 text-center col-padding animate-box">
				<a href="#" class="work" style="background-image: url(images/portfolio-7.jpg);">
					<div class="desc">
						<h3>Project Name</h3>
						<span>Brading</span>
					</div>
				</a>
			</div>
			<div class="col-md-3 text-center col-padding animate-box">
				<a href="#" class="work" style="background-image: url(images/portfolio-8.jpg);">
					<div class="desc">
						<h3>Project Name</h3>
						<span>Illustration</span>
					</div>
				</a>
			</div>
		</div>
	</div>
</div>

templates/portfolio/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello PortfolioController!
{% endblock %}

{% block stylesheets %}
	<link href="https://fonts.googleapis.com/css?family=Space+Mono" rel="stylesheet">
	<link
	href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
	<!-- Animate.css -->
	<link
	rel="stylesheet" href="{{ asset('css/animate.css') }}">
	<!-- Icomoon Icon Fonts-->
	<link
	rel="stylesheet" href="{{ asset('css/icomoon.css') }}">
	<!-- Bootstrap  -->
	<link
	rel="stylesheet" href="{{ asset('css/bootstrap.css') }}">
	<!-- Theme style  -->
	<link
	rel="stylesheet" href="{{ asset('css/style.css') }}">

	<!-- Modernizr JS -->
	<script src="{{ asset('js/modernizr-2.6.2.min.js') }}"></script>
{% endblock %}

{% block body %}
	<div class="fh5co-loader"></div>

	<div id="page">
		{{include('portfolio/_header.html.twig')}}
		{{include('portfolio/_about.html.twig')}}
		{{include('portfolio/_resume.html.twig')}}
		{{include('portfolio/_features.html.twig')}}
		{{include('portfolio/_skills.html.twig')}}
		{{include('portfolio/_works.html.twig')}}
		{{include('portfolio/_blog.html.twig')}}
		{{include('portfolio/_hire.html.twig')}}
		{{include('portfolio/_contact.html.twig')}}
		{{include('portfolio/_map.html.twig')}}


	</div>

	{{include('portfolio/_footer.html.twig')}}
{% endblock %}

{% block javascripts %}

	<!-- jQuery -->
	<script src="{{ asset('js/jquery.min.js') }}"></script>
	<!-- jQuery Easing -->
	<script src="{{ asset('js/jquery.easing.1.3.js') }}"></script>
	<!-- Bootstrap -->
	<script src="{{ asset('js/bootstrap.min.js') }}"></script>
	<!-- Waypoints -->
	<script src="{{ asset('js/jquery.waypoints.min.js') }}"></script>
	<!-- Stellar Parallax -->
	<script src="{{ asset('js/jquery.stellar.min.js') }}"></script>
	<!-- Easy PieChart -->
	<script src="{{ asset('js/jquery.easypiechart.min.js') }}"></script>
	<!-- Google Map -->
	<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&sensor=false"></script>
	<script src="{{ asset('js/google_map.js') }}"></script>

	<!-- Main -->
	<script src="{{ asset('js/main.js') }}"></script>

{% endblock %}